spring:
  profiles.active: production
---
spring:
  config.activate.on-profile: test
  datasource.url: jdbc:h2:mem:test
  jpa.hibernate.ddl-auto: create
logging.level:
  root: info
---
spring:
  config.activate.on-profile: development
  datasource:
    url: jdbc:h2:file:~/.h2/pilotlog-dev
  jpa:
    hibernate.ddl-auto: create
    open-in-view: false
    show_sql: true
    defer-datasource-initialization: true
  sql.init:
    platform: dev
    mode: always
logging.level:
  root: info
---
spring:
  config.activate.on-profile: production
  datasource:
    url: jdbc:h2:file:~/.h2/pilotlog
    username: sa
    password:
  h2.console.enabled: true
  jpa:
    hibernate.ddl-auto: update
    open-in-view: false
    show_sql: false
  sql.init:
    mode: never
logging:
  file.name: ${HOME}/.h2/logs/pilotlog.log
  level:
    root: info
