spring:
  profiles.active: production
logging:
  config: classpath:logback.xml
---
spring:
  profiles: test
  datasource.url: jdbc:h2:mem:test
  jpa.hibernate.ddl-auto: create
logging.level:
  org.flightgear.pilotlog: info
---
spring:
  profiles: development
  datasource:
    url: jdbc:h2:file:~/.h2/pilotlog-dev
    platform: dev
  jpa.hibernate.ddl-auto: create
  thymeleaf.cache: false
logging.level:
  org.flightgear.pilotlog: info
management:
  security.enabled: false
---
spring:
  profiles: production
  datasource.url: jdbc:h2:file:~/.h2/pilotlog
  jpa.hibernate.ddl-auto: update
  thymeleaf.cache: true
logging.level:
  org.flightgear.pilotlog: warn
management:
  security.enabled: true
  
